### PR TITLE
Add support for the '|' operator in paths.

### PR DESCRIPTION
**Pull request by beevik**
Ok I added support for the OR operator in paths.  Please try it out and let me know if it works for you.

I tagged this change as v0, so you can pull this repo from gopkg.in/beevik/etree.v0

### CODE REVIEW

**Comment by beevik** [comment]
I tagged this change as v0, so you can pull this repo from gopkg.in/beevik/etree.v0

**Comment by suntong** [comment]
Thanks. Will try tomorrow.

**Comment by suntong** [comment]
Thanks. 

Should work for case like this as well:

`.//book[author|title]`

Will try tomorrow.

**Comment by beevik** [comment]
The more I think about this change, the more I'm not sure I like it.

To properly support union expressions using the '|' operator, I really need to support general  path expressions with parentheses.  When I originally wrote the path code, I modeled it after the python etree system, which also supports a pretty simple XPath-like algorithm.  It isn't designed to handle complicated XPath expressions.  I'd like to keep this code simple and small, so I'm going to think about whether I should support this feature.

**Comment by suntong** [comment]
Yeah, agree. But please keep your existing changes.

**Comment by suntong** [comment]
Yep, it works great. Please merge to head. Thanks.

**Comment by beevik** [comment]
I'm working on a rewrite of the path code that should make more XPath-like behaviors possible, so I think I will hold off on merging this.

**Comment by suntong** [comment]
Sure. For a moment, I thought you're going to reject the merge. Glad that it's a much better option.

**Comment by alexellis** [comment]
How is this progressing? @beevik @suntong

**Comment by beevik** [comment]
@alexellis Sorry, I haven't hard any time to devote to this. It turned out to be a bigger change than I originally anticipated.  Perhaps some day I'll get time to do it.

**Comment by alexellis** [comment]
That's fair. Is it worth putting a deprecation or help wanted notice on the Readme so people can chose another library? This was the first one I found when looking for XML Dom for Golang.

**Comment by lawrencejones** [comment]
Hey @beevik, I was having some serious issues running etree against an XPath like:

```
//node/instance_attributes/nvpair[@value='STREAMING|SYNC']/../..
```

I was totally unsure why this was occurring, and was looking at the code in my vendor dir and comparing it against master. It was only then that I realised what I had in vendor wasn't ever in master, which was super confusing.

Two points that I feel are worth making- it appears you merged this to master, then reverted it by removing the commits from the branch. That's quite a scary thing when you're working with a language like go, where your deps are taken from Github! It would have made it a lot easier for me to see what had happened if you had reverted your change and left the history behind.

Secondly, I'm ridiculously happy that you reverted this, as it broke a legitimate use case that I had for your library. Any approach to add this operator to the XPath syntax would need to provide some way of escaping the token in selector content, or a better method of parsing to make sure it works regardless.

Cheers for the great work on the library!

**Comment by beevik** [comment]
@lawrencejones Yes, you're right, I shouldn't have used the `v0` tag as it confusing vendoring, which I think was still somewhat new to go when I first did it.  I should probably just make an official `v1` at this point.  Sorry for the confusion.

I've removed the `v0` tag.

**Comment by beevik** [comment]
Closing this PR, since I replaced it with a better one.

**Comment by beevik** [comment]
I opened a new pull-request (https://github.com/beevik/etree/pull/50) that has a working version of "OR" paths.

I am working on optimizing it, because it generates too much garbage right now.

**Pull request closed without merging**
